create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_type text not null,
  detail jsonb
);

alter table public.logs enable row level security;

create policy "Enable insert for authenticated users only"
on public.logs for insert
to authenticated
with check (true);

create policy "Enable select for authenticated users only"
on public.logs for select
to authenticated
using (true);
